name: Test SSH

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test SSH connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            echo "==== CONNECTED ===="
            whoami
            hostname